
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/DissOx.RData")
attach(DissOx)
Boxplot(DO~Pre.Post, data=DissOx, id=list(method="y"))
normalityTest(DO ~ Pre.Post, test="shapiro.test", data=DissOx)
shapiro.test(DO[Pre.Post=="Pre2008"])
shapiro.test(DO[Pre.Post=="Post2008"])
library(abind, pos=32)
t.test(DO~Pre.Post, alternative='two.sided', conf.level=.95, 
  var.equal=FALSE, data=DissOx)
with(DissOx, tapply(DO, Pre.Post, median, na.rm=TRUE))
wilcox.test(DO ~ Pre.Post, alternative="two.sided", data=DissOx)
perm(DO, Pre.Post, nrep=10000)
permTS(DO~Pre.Post, method="exact.mc", control=permControl(nmc=5000, p.conf.level = 0.95))
0.95))
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/specapic.rda")
attach(specapic)
with(specapic, tapply(spcap, rock, median, na.rm=TRUE))
kruskal.test(spcap ~ rock, data=specapic)
pairwise.wilcox.test(spcap,rock,"BH")
perm1way(spcap,rock)
with(specapic, tapply(spcap, rock, var, na.rm=TRUE))
leveneTest(spcap ~ rock, data=specapic, center="median")
normalityTest(spcap ~ rock, test="shapiro.test", data=specapic)
fligner.test(spcap, rock)

