
setwd("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data")
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/STREAMS.RData")
attach(STREAMS)
library(abind, pos=31)
local({
  .Table <- xtabs(~STATE+STREAM, data=STREAMS)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  Table2 <- xtabs(~STATE+STREAM, data=STREAMS)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
  cat("\nChi-square components:\n")
  print(round(.Test$residuals^2, 2))
})
chisq.test(Table2, simulate.p.value=TRUE, B=10000)
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/OKx.rda")
attach(OKx)
local({
  .Table <- xtabs(~DATA+SUBUNIT, data=OKx)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  Table2 <- xtabs(~DATA+SUBUNIT, data=OKx)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
  cat("\nChi-square components:\n")
  print(round(.Test$residuals^2, 2)) 
  print(fisher.test(.Table))
})
chisq.test(Table2, simulate.p.value=TRUE, B=10000)
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/SedPb.RData")
attach(SedPB)
Boxplot( ~ Post.Pre, data=SedPb, id=list(method="y"))
signtest(Post.Pre,0,alt="g")
with(SedPb, median(Yr2001 - Yr1996, na.rm=TRUE)) # median difference
with(SedPb, wilcox.test(Yr2001, Yr1996, alternative='two.sided', 
  paired=TRUE))
with(SedPb, median(Yr2001 - Yr1996, na.rm=TRUE)) # median difference
with(SedPb, wilcox.test(Yr2001, Yr1996, alternative='greater', paired=TRUE))
normalityTest(~Post.Pre, test="shapiro.test", data=SedPb)
with(SedPb, (t.test(Yr2001, Yr1996, alternative='two.sided', conf.level=.95,
   paired=TRUE)))
permMatched(Yr2001, Yr1996)
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/DP2v3_TP.RData")
attach(DP2v3_TP)

with(DP2v3_TP, median(DP2 - DP3, na.rm=TRUE)) # median difference
with(DP2v3_TP, wilcox.test(DP2, DP3, alternative='two.sided', paired=TRUE))
Boxplot( ~ DP2, data=DP2v3_TP, id=list(method="y"))
Boxplot( ~ DP3, data=DP2v3_TP, id=list(method="y"))
boxplot(DP2,DP3, main="Boxplots of TP",ylab="TP", xlab="site", names=c("DP2","DP3"), col="light blue")
Boxplot( ~ DP2minusDP3, data=DP2v3_TP, id=list(method="y"))
with(DP2v3_TP, (t.test(DP2, DP3, alternative='two.sided', conf.level=.95, 
  paired=TRUE)))
perm1sample(DP2minusDP3)
Bootmean(DP2minusDP3)
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/arsenic.rda")
attach(arsenic)
load("C:/Users/lilia/Desktop/Applied Environmental Statistics/AES1 Online 2_5/AES1 Online 2_5/AES1 Data/NEB2.RData")
attach(NEB2)
Boxplot( ~ NO3_84, data=NEB2, id=list(method="y"))
normalityTest(~NO3_84, test="shapiro.test", data=NEB2)
t.test(NO3_84, alternative ="greater", mu=10)

